# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ju Min Lee
title: M.S Ph.D student
email: jumin@yonsei.ac.kr
website: www.github.com/jumin-lee/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  jumin-lee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0000-5941-3588

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# Profile should go here
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jumin and I'm a M.S Ph.D student in Yonsei University, Compiler Optimization Lab(CoreLab)

  Research interests in: <mark>Compiler Optimization</mark>, <mark>GPU Architecture</mark>, <mark>Real-time System</mark>
content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Yonsei University
        caption: 2017 - 2023
#        sub_title: Bachelor of Engineering
#        quote: >
 #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          <mark>Bachelor of Engineering</mark>
          
          Department of Electrical and Electroninc Engineering
      - layout: left
        title: University of California Irvine
        caption: 2019.01 - 2019.07
#        sub_title: Transfer Student
#        description: | 
#          <mark>M.S/Ph.D Candidate</mark>
        
          Current research on Compiler Optimization Research Lab(CoreLab)
      - layout: left
        title: Yonsei University
        caption: 2024 - Present
#        sub_title: M.S/Ph.D candidate
        description: | 
          <mark>M.S/Ph.D Candidate</mark>
          Advisor: Hanjun Kim
        
          Current research on Compiler Optimization Research Lab(CoreLab)
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **SnakeByte: A TLB Design with Adaptive and Recursive Page Merging in GPUs** *(HPCA'23)*
      
        Jiwon Lee, **Ju Min Lee**, Yunho Oh, William J. Song, Won Woo Ro
      - **DaCapo: Automatic Bootstrapping Management for Efficient Fully Homomorphic Encryption** *(Security'24)*
      
        Seonyoung Cheon, Yongwoo Lee, Dongkwan Kim, **Ju Min Lee**, Sunchul Jung, Taekyung Kim, Dongyoon Lee, Hanjun Kim
      - **TeMCO: Tensor Memory Compiler Optimization across Tensor Decompositions in Deep Learning Inference** *(ICPP'24)*
      
        Seungbin Song, **Ju Min Lee**, Haeeun Jeong, Hyunho Kwon, Shinnung Jeong, Jaeho Lee, and Hanjun Kim      
  - title: Teaching
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Teaching Assistant**, EEE2020: DATA STRUCTURE, Yonsei University 
      
        Spring 2024
        
  - title: Recognition
    layout: list
    content:
      - layout: left
        title: The 30th Humantech Paper Awards
        caption: Feb 2024
        description: |
          [[Silver Prize]](https://github.com/jumin-lee/jumin-lee.github.io/blob/master/images/humantech2023.pdf)
          
          Samsung Electronics Co., Ltd., Republic of Korea
        
  - title: Experience
    layout: text
    content: |
      - **Graduate Research Assistant**, Compiler Research Lab (CoreLab), Yonsei University ( Mar 2023 - Present)

        Research on DNN inference and GPU scheduling for multi-tenant system in embedded system
      - **Undergraduate Research Assistant**, Compiler Research Lab (CoreLab), Yonsei University (Jul 2022 - Feb 2023)

        Research on real-time cores and DNN inference in compiler research lab
      - **Undergraduate Research Assistant**, Computer Architecture and System Lab, Yonsei University (Jul 2020 - Jun 2022)

        Research on GPU architecture in consideration for memory management
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
